### PR TITLE
Fix anonymous enum elements enforcing their tag

### LINKED ISSUE #514: tag mismatch
### Issue description:
Assigning a tagged value to an array cell indexed with an enum constant makes the compiler print warning 213 (tag mismatch), even though the array has the same tag.

### Minimal complete verifiable example (MCVE):
```Pawn
#include <a_samp>

const TD_0 = 0;
enum { TD_1 = 1 };
new Text:textdraws[2];

main()
{
    // no warnings/errors on the following line, as `TD_0`
    // is a regular constant, not an enum element
    textdraws[TD_0] = TextDrawCreate(0.0, 0.0, "-");

    // warning 213: tag mismatch: expected tag none ("_"), but found "Text"
    textdraws[TD_1] = TextDrawCreate(0.0, 0.0, "-");
}
```
It seems that if an array is indexed with an enum constant, the tag of the said constant somehow overrides the array tag, so in the above example the compiler expects no tag (`_:`) instead of `Text:`, which doesn't seem to be correct.

Originally reported by the forum user 'tnc' here: https://pro-pawn.ru/showthread.php?2207-Pawn-compiler-%283-10%29&p=96537&viewfull=1#post96537

### Workspace Information:

* Compiler version: 3.2.3664, 3.10.1 - 3.10.10
* Command line arguments provided (or sampctl version):
* Operating System:

### PR DESCRIPTION
**Pull request by Daniel-Cortez**
**What this PR does / why we need it**:

Fixes anonymous enum elements overriding the resulting tag when they're used for array indexing, as described in #514.

**Which issue(s) this PR fixes**:

Fixes #514

**What kind of pull this is**:

* [x] A Bug Fix
* [ ] A New Feature
* [ ] Some repository meta (documentation, etc)
* [ ] Other

**Additional Documentation**:

### CODE REVIEW

File: source/compiler/sc3.c [hunk 1]
```diff
@@ -1832,8 +1832,6 @@ static int hier1(value *lval1)
       if (lval2.ident==iCONSTEXPR && lval2.sym!=NULL
           && lval2.sym->dim.array.length>0 && sym->dim.array.level==0)
       {
-        lval1->tag=lval2.sym->x.tags.index;
```
Comment (Daniel-Cortez) [inline source/compiler/sc3.c:1835]: I removed these two lines, as they turned out to be duplicate code. There's already code that does the same thing (saves the tag and the enum field size into the resulting value) at lines 1784-1785.

File: source/compiler/sc3.c [hunk 2]
```diff
@@ -1832,8 +1832,6 @@ static int hier1(value *lval1)
...
-        lval1->constval=lval2.sym->dim.array.length;
         if (lval2.tag==sym->x.tags.index && lval1->constval>1 && matchtoken('[')) {
```
Comment (Daniel-Cortez) [inline source/compiler/sc3.c:1835]: I removed these two lines, as they turned out to be duplicate code. There's already code that does the same thing (saves the tag and the enum field size into the resulting value) at lines 1784-1785.

File: source/compiler/sc3.c [hunk 3]
```diff
@@ -1832,8 +1832,6 @@ static int hier1(value *lval1)
       if (lval2.ident==iCONSTEXPR && lval2.sym!=NULL
           && lval2.sym->dim.array.length>0 && sym->dim.array.level==0)
       {
-        lval1->tag=lval2.sym->x.tags.index;
-        lval1->constval=lval2.sym->dim.array.length;
```
Comment (Daniel-Cortez) [inline source/compiler/sc3.c:1836]: I removed these two lines, as they turned out to be duplicate code. There's already code that does the same thing (saves the tag and the enum field size into the resulting value) at lines 1784-1785.
